_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (70000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/R_101_FPN_base"
